baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Tom Barrasso'
theme = 'henry'
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON", "SEARCH"]

[params]
bioUrl = "https://barrasso.me"
summary = "People, Process, Programming"
enableSearch = true
enablePagination = true
avatar = "/images/portraits.jpg"
sitename = "barrasso.me"
github = "https://github.barrasso.me"
medium = "https://medium.barrasso.me"
linkedin = "https://linkedin.barrasso.me"
enableRobotsTXT = true
reshare = false
invisibleTypes = ["resume"]
invisibleSections = ["offline", "log"]

[params.search]
enabled = true
[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.author]
name = "Tom Barrasso"
email = "blog@barrasso.me"
url = "https://barrasso.me"
avatar = "/images/portraits.jpg"

[[params.authors]]
name = "Tom Barrasso"
url = "https://barrasso.me"

[params.copyright]
holder = "Thomas Barrasso"
year = "2025"

[params.copyright.contentLicense]
name = "Creative Commons Attribution 4.0 License"
url = "https://creativecommons.org/licenses/by/4.0/"

[params.copyright.codeLicense]
name = "Apache 2.0 License"
url = "https://www.apache.org/licenses/LICENSE-2.0"

[params.skills]
languages = ["TypeScript", "JavaScript", "Java", "Go"]
frontend = ["React", "Svelte"]
backend = ["Node.js", "Ruby on Rails"]
devops = ["Docker", "AWS", "Linux"]
databases = []
practices = [
  "Program Management",
  "Product Management",
  "Technical Communication",
  "Data Visualization",
  "Risk Management",
]

[privacy]
[privacy.youTube]
disable = false
privacyEnhanced = true
