baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Tom Barrasso'
theme = 'henry'
disableHugoGeneratorInject = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON", "SEARCH"]

[params]
bioUrl = "https://barrasso.me"
summary = "Code, Culture, Creativity"
enableSearch = true
enablePagination = true
avatar = "/images/portraits.jpg"
sitename = "barrasso.me"
github = "https://github.barrasso.me"
medium = "https://medium.barrasso.me"
linkedin = "https://linkedin.barrasso.me"
enableRobotsTXT = true
reshare = false
invisibleTypes = ["resume"]

[params.search]
enabled = true
[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.author]
name = "Tom Barrasso"
email = "blog@barrasso.me"
url = "https://barrasso.me"
avatar = "/images/portraits.jpg"

[[params.authors]]
name = "Tom Barrasso"
url = "https://barrasso.me"

[params.copyright]
holder = "Thomas Barrasso"
year = "2025"

[params.copyright.contentLicense]
name = "Creative Commons Attribution 4.0 License"
url = "https://creativecommons.org/licenses/by/4.0/"

[params.copyright.codeLicense]
name = "Apache 2.0 License"
url = "https://www.apache.org/licenses/LICENSE-2.0"

[params.skills]
languages = ["TypeScript", "JavaScript", "Java", "Go", "Ruby on Rails", "Bash"]
frontend = ["React", "Svelte", "Vue.js", "HTML", "CSS"]
backend = ["Node.js", "Next.js", "tRPC", "WebSockets"]
devops = ["Docker", "AWS", "Cloudflare", "CI/CD", "Linux", "Git"]
databases = ["SQLite", "PostgreSQL", "DynamoDB", "Redis"]
practices = ["Program Management", "Product Management", "Technical Communication", "Data Visualization", "Threat Modeling"]

[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = true
