baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Tom Barrasso'
theme = 'henry'
disableHugoGeneratorInject = true

[outputs]
home = ["HTML", "RSS", "JSON", "SEARCH"]

[params]
bioUrl = "https://barrasso.me"
summary = "Code, Culture, Creativity"
enableSearch = true
enablePagination = true
avatar = "/images/portraits.jpg"
sitename = "barrasso.me"
github = "https://github.com/tombarr"
enableRobotsTXT = true

[params.search]
enabled = true
[outputFormats.SEARCH]
baseName = "search"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.author]
name = "Tom Barrasso"
email = "blog@barrasso.me"
url = "https://barrasso.me"
avatar = "/images/portraits.jpg"

[[params.authors]]
name = "Tom Barrasso"
url = "https://barrasso.me"

[params.copyright]
holder = "Thomas Barrasso"
year = "2025"

[params.copyright.contentLicense]
name = "Creative Commons Attribution 4.0 License"
url = "https://creativecommons.org/licenses/by/4.0/"

[params.copyright.codeLicense]
name = "Apache 2.0 License"
url = "https://www.apache.org/licenses/LICENSE-2.0"
